---
version: "2.1"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /athenamedia/Appdata/Jackett:/config
    ports:
      - 9117:9117
    restart: always
  transmission:
  radarr:
  sonarr:
  lidarr:
  plex:
  ombi:
