---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    network_mode: "host"
    tty: true
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true # optional
      - RUN_OPTS= # optional
    volumes:
      - /athenamedia/Appdata/Jackett:/config
    ports:
      - 9117:9117
    security_opt:
      - apparmor=unconfined
    restart: always
